[build]
  command = "npm run build"
  publish = "outputs"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/create-square-checkout"
  to = "/.netlify/functions/create-square-checkout"
  status = 200
